DROP TABLE IF EXISTS ASSET_INFO;
CREATE TABLE ASSET_INFO
(
  USER_ID      VARCHAR(32) COMMENT '用户ID',
  ASSET_ID     VARCHAR(32)   NOT NULL COMMENT 'caichanID',
  PASSWORD     VARCHAR(2048) NOT NULL COMMENT '密码',
  PHONE        VARCHAR(20) COMMENT '电话',
  E_MAIL       VARCHAR(128) COMMENT '邮箱',
  MAIN_PAGE    VARCHAR(128) COMMENT '邮箱',
  DESCRIPTION  VARCHAR(128) COMMENT '邮箱',
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
  PRIMARY KEY (USER_ID, ASSET_ID)
)
  ENGINE = INNODB
  DEFAULT CHARSET = utf8;
