DROP TABLE IF EXISTS FORUM_POSTS;
CREATE TABLE FORUM_POSTS
(
  TOPIC_URL       VARCHAR(64) PRIMARY KEY COMMENT '5',
  PARTITION   VARCHAR(2) NOT NULL COMMENT '4',
  TOPIC_TITLE  VARCHAR(1624) NOT NULL COMMENT '3',
  TORRENT_URL VARCHAR(1624) NOT NULL COMMENT '2',
  TORRENT_HASH VARCHAR(1624) NOT NULL COMMENT '1',
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期'
) ENGINE = INNODB
  DEFAULT CHARSET = utf8;

