DROP TABLE IF EXISTS FORUM_POSTS;
CREATE TABLE FORUM_POSTS
(
  TOPIC_URL       VARCHAR(64) PRIMARY KEY COMMENT '帖子地址',
  TOPIC_PARTITION   VARCHAR(4) NOT NULL COMMENT '帖子分区',
  TOPIC_TITLE  VARCHAR(1024) NOT NULL COMMENT '帖子标题',
  TORRENT_URL VARCHAR(256) DEFAULT '0' COMMENT '种子地址',
  TORRENT_HASH VARCHAR(129) DEFAULT '0' COMMENT '种子hash',
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期'
) ENGINE = INNODB
  DEFAULT CHARSET = utf8;

