DROP TABLE IF EXISTS TOPIC_INFO;
CREATE TABLE TOPIC_INFO
(
  id           int auto_increment PRIMARY KEY,
  TOPIC_URL    VARCHAR(128) COMMENT '帖子地址',
  TOPIC_FID    VARCHAR(4)    NOT NULL COMMENT '帖子分区',
  TOPIC_TITLE  VARCHAR(2048) NOT NULL COMMENT '帖子标题',
  TOPIC_STATUS VARCHAR(4) DEFAULT '0' COMMENT '-1 processing 0 未处理 1 URL已处理 2 图片URL异常 3 种子URL异常 4 所有URL异常',
  CREATED_DATE TIMESTAMP  DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  UPDATED_DATE TIMESTAMP  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期'
) ENGINE = INNODB
  DEFAULT CHARSET = utf8;
alter table TOPIC_INFO
  add constraint UK_TOPIC_INFO unique (TOPIC_URL);

ALTER TABLE TOPIC_INFO
  ADD INDEX TOPIC_STATUS_IDX (TOPIC_STATUS);
