DROP TABLE IF EXISTS HTML_INFO;
CREATE TABLE HTML_INFO
(
  id           int auto_increment PRIMARY KEY,
  TOPIC_URL    VARCHAR(128) COMMENT '帖子地址',
  HTML    TEXT COMMENT '种子地址 ',
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
  foreign key (TOPIC_URL) references TOPIC_INFO (TOPIC_URL)
) ENGINE = INNODB
  DEFAULT CHARSET = utf8
  ROW_FORMAT=COMPRESSED;

