version: '3.7'

services:
  mysql_master:
    &mysql
    container_name: mysql_master
    image: 'mysql:8.0.16'
    networks:
      cluster-network:
        ipv4_address: 172.28.0.11
    environment:
#      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./conf/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./conf/mysql/master.cnf:/etc/mysql/conf.d/master.cnf
      - ${DOCKER_VOLUME}/mysql/master:/var/lib/mysql
  mysql_slave:
    <<: *mysql
    container_name: mysql_slave
    networks:
      cluster-network:
        ipv4_address: 172.28.0.12
    volumes:
      - ./conf/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./conf/mysql/slave.cnf:/etc/mysql/conf.d/slave.cnf
      - ${DOCKER_VOLUME}/mysql/slave:/var/lib/mysql
#  eithi9ram2Saeji5Nai7miShohzop2Uc
#  nav9ahdong5NohNgoopooSh4eideijoo
#  ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'YourPassword';
#  CREATE USER 'username'@'host' IDENTIFIED WITH mysql_native_password BY 'password';