create table account_info
(
  id           int auto_increment PRIMARY KEY,
  ACCOUNT      VARCHAR(128) PRIMARY KEY COMMENT '账户ID',
  ACCOUNT_TYPE TINYINT,
  PASSWORD     VARCHAR(2048) NOT NULL COMMENT '密码',
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期'
) ENGINE = INNODB
  DEFAULT CHARSET = utf8;

ALTER TABLE account_info
  ADD INDEX TORRENT_FILE_ID_IDX (ACCOUNT);