DROP TABLE IF EXISTS service_cipher.SECRET_KEY_INFO;
CREATE TABLE service_cipher.SECRET_KEY_INFO
(
  KEY_ID           VARCHAR(32) PRIMARY KEY COMMENT 'keyid',
  PUBLIC_KEY       VARCHAR(2048) NOT NULL COMMENT '公钥',
  PRIVATE_KEY      VARCHAR(2048) NOT NULL COMMENT '私钥',
  CIPHER_ALGORITHM VARCHAR(16)   NOT NULL COMMENT 'cipher Algorithm',
  CREATED_DATE     TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  UPDATED_DATE     TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期'
) ENGINE = INNODB
  DEFAULT CHARSET = utf8;


