CREATE TABLE TOPIC_INFO_BAK
SELECT * FROM TOPIC_INFO WHERE 1=1;

CREATE TABLE IMAGE_INFO_BAK
SELECT * FROM IMAGE_INFO WHERE 1=1;

CREATE TABLE TORRENT_INFO_BAK
SELECT * FROM TORRENT_INFO WHERE 1=1;

CREATE TABLE HTML_INFO_BAK
SELECT * FROM HTML_INFO WHERE 1=1;