drop table IMAGE_INFO_BAK;
drop table TORRENT_INFO_BAK;
drop table HTML_INFO_BAK;
drop table TOPIC_INFO_BAK;

CREATE TABLE TOPIC_INFO_BAK
SELECT * FROM TOPIC_INFO WHERE 1=1;

CREATE TABLE IMAGE_INFO_BAK
SELECT * FROM IMAGE_INFO WHERE 1=1;

CREATE TABLE TORRENT_INFO_BAK
SELECT * FROM TORRENT_INFO WHERE 1=1;

CREATE TABLE HTML_INFO_BAK
SELECT * FROM HTML_INFO WHERE 1=1;


insert into TOPIC_INFO(TOPIC_URL, TOPIC_FID, TOPIC_TITLE, TOPIC_STATUS, CREATED_DATE, UPDATED_DATE) SELECT
                                                                                                       TOPIC_URL, TOPIC_AREA, TOPIC_TITLE, TOPIC_STATUS, CREATED_DATE, UPDATED_DATE
from TOPIC_INFO_BAK